version: '3'
services:
  go-editor-db:
    image: mysql:8
    container_name: go-editor-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: code_db
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql-volume/lib/mysql:/var/lib/mysql
  go-editor-backend:
    image: go-editor-backend:latest
    container_name: go-editor-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    depends_on:
      - go-editor-db
  go-editor-frontend:
    image: go-editor-frontend:latest
    container_name: go-editor-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3333:80"
    depends_on:
      - go-editor-backend
